[package]
name = "credentials"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v1.0.1" }

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
casm = false
