[workspace]
members = [
  "credentials",
  "shadow",
  "shared",
]

[workspace.dependencies]
starknet = "2.15.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.55.0" }
